### ISSUE TITLE
Curve Fitting Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/curve-fitting#19]
## Design
- [ ] **Design doc created** (Date: / / / )
- [ ] **Legacy sim docs/info gathered**
- [ ] **Learning goals and standards identified** (Date: / / / )
- [ ] **Design concept complete**  (Date: / / / )
- [ ] **Wireframes complete** (Date: / / / ) 
- [ ] **Mockups complete** (Date: / / / ) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Design doc sent for quote** (Date: / / / )  
- [ ] **Visual and interaction review of first deliverable**
- [ ] **Interviews complete** (Date: / / / ) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: / / / ) 
  - [ ] Performance acceptable
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [ ] Check compatible activities  
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Teacher guide
  - [ ] Activities and gooru spreadsheet
  - [ ] Notify translators?
  - [ ] Sim primer
  - [ ] Verify credits
- [ ] **Hold postmortem if applicable** (Date: / / / ) 

## Implementation
- [ ] **Sim repo created** (Date: / / / ) 
  - [ ] Collaborators added (such as 3rd party, QA team, designers, etc) 
  - [ ] Sim added to active repos list in chipper
  - [ ] Sim suggestions doc reviewed
  - [ ] Unfuddle tickets reviewed
  - [ ] Existing sim tested for bugs, issues reported in repo
  - [ ] Port existing strings (IF ANY) and commit to the GitHub repo
  - [ ] Implementation details added to design spec
  - [ ] Paste snapshot of code review checklist into repo issue
- [ ] **Initial development started** (Date: / / / ) 
- [ ] **Sim feature complete** (Date: / / / ) 
- [ ] **Code review complete** (Date: / / / ) 
  - [ ] Code review checklist
  - [ ] Model description 
- [ ] **PhET tweaks after sim acceptance** (Date: / / / ) 
- [ ] **Published** (Date: / / / ) 
  - [ ] Update repo README to published template

## QA
- [ ] **Dev testing complete** (Date: / / / ) 
- [ ] **First release candidate** (Date: / / / ) 
- [ ] **Sim accepted from third party** (Date: / / / )
- [ ] **Test matrix deemed complete**

**Comment by ariel-phet** [comment]
Note to self...change to modern checklist

**Comment by amanda-phet** [comment]
I'm still waiting on https://github.com/phetsims/website/issues/954 to be fixed so I can finish up transferring activities over.

**Comment by ariel-phet** [comment]
# Curve Fitting Port Master Checklist

## Design
- [ ] **Sim folder and design doc created** (Date: 09/22/2015) 
  - [ ] Create sim folder in [PhET Sim Design Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYUUhvZnlCUDF0bGc) using phet-docs account
  - [ ] Place design doc in the sim folder
- [ ] **Legacy sim docs/info gathered**
  - [ ] [Sim suggestions doc](https://phet.unfuddle.com/a#/projects/9404/notebooks/3863/pages/105821) reviewed
  - [ ] Unfuddle tickets reviewed ([searching tickets](https://github.com/phetsims/phet-info/blob/master/issue-info/unfuddle-ticket-search.md))
- [ ] **Learning goals and standards identified** (Date: //)
- [ ] **Design concept complete**  (Date: //)
- [ ] **Wireframes complete** (Date: //) 
- [ ] **Mockups complete** (Date: //) 
  - [ ] Mockups checked for colorblind and greyscale
- [ ] **Features for PhET-iO discussion** 
- [ ] **Interviews complete** (Date: //) 
  - [ ] Results reported to team
  - [ ] Notes pasted into design doc
  - [ ] Back-up of interviews
- [ ] **Lead designer "sign off"** (Date: //) 
  - [ ] Performance acceptable
  - [ ] Carefully review ?showPointerAreas
  - [ ] No new feature requests
- [ ] **Pre-publication items** 
  - [ ] Auxilary screenshots (up to 3 additional)
  - [ ] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [ ] Accessibility features
  - [ ] Email announcement language
  - [ ] Teacher Guide created, uploaded, and added to sim design folder
  - [ ] Sim primer draft
  - [ ] [LoL icons](https://docs.google.com/document/d/1GmLNE31gs8hQYGze3xwmN9k7B6gu7lQ7wJe2phqdH9Y/edit) for each screen created and uploaded to Drive
  - [ ] LoL [metadata](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429) for each screen (description, vocab words, questions for before/after sim use)
- [ ] **Post-publication items** 
  - [ ] Share new features, design challenges, and treats with group!
  - [ ] Review legacy gold star activities, copy over if appropriate
  - [ ] Email announcement language
  - [ ] Deliver to [Legends of Learning](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=0)
  - [ ] Sim primer (create issue, publish ideally within 1 month of live sim)
  - [ ] Hold postmortem if applicable (Date: //) 

## Implementation
- [ ] **Repository created** (Date: //)
  - [ ] Simulation added to [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)
  - [ ] simula-rasa used to create project skeleton
  - [ ] README.md created using `grunt unpublished-readme`
  - [ ] Collaborators added (Developer team, QA team, designers, etc)
  - [ ] standard GitHub label set applied
  - [ ] repository added to perennial/data/active-repos
- [ ] **Development started** (Date: //)
- [ ] **Sim is "feature complete"** (Date: //) 
- [ ] **Code review completed** (Date: //) 
- [ ] **Pre-publication items** 
  - [ ] Main screenshot (read [this](https://github.com/phetsims/QA/blob/master/doc/qa-book.md#screenshots))
  - [ ] Verify credits with lead (Team, Contributors, QA, Graphic Arts, Sound Design, any Thanks)
- [ ] **Published** (Date: //) 
  - [ ] Mark the sim as published in [responsible_dev.md](https://github.com/phetsims/phet-info/blob/master/sim-info/responsible_dev.md)

## QA
- [ ] **Legacy sim tested for bugs**; issues reported in repo
- [ ] **Dev testing started** (Date: //) 
- [ ] **Dev testing complete** (Date: //) 
- [ ] **First RC published** (Date: //)
  - [ ] Test matrices put in [Testing Matrices Folder](https://drive.google.com/drive/folders/0B6CMwxdP0NGYbW9fTGNCODdYVjQ)
- [ ] **RC testing completed** (Date: //)
